services:
    phpbbitalia.topten.listener:
        class: staffit\toptentopics\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @template
            - @auth
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
